spring:
  application:
    name: rabbitmq-example

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

rabbitmq:
  exchange: exchange
  queue: queue
  routingkey: routingkey



